sudo: required
services:
  - docker

before_install:
  - docker build -t schaefercode/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true schaefercode/react-test npm test

after_success:
  - docker build -t schaefercode/multi-client ./client
  - docker build -t schaefercode/multi-nginx ./nginx
  - docker build -t schaefercode/multi-server ./server
  - docker build -t schaefercode/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push schaefercode/multi-client
  - docker push schaefercode/multi-nginx
  - docker push schaefercode/multi-server
  - docker push schaefercode/multi-worker
