sudo: required
services:
  - docker

before_install:
  - docker build -t igloomane/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true igloomane/react-test npm test

after_success:
  - docker build -t igloomane/multi-client:v5 ./client
  - docker build -t igloomane/multi-nginx ./nginx
  - docker build -t igloomane/multi-server ./server
  - docker build -t igloomane/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push igloomane/multi-client:v5
  - docker push igloomane/multi-nginx
  - docker push igloomane/multi-server
  - docker push igloomane/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-869803486436
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
